language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - python setup.py install
  - pip install tox-travis coveralls coverage
script:
  - tox
  - coverage combine
  - coverage report
after_success:
  - coveralls