language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - python setup.py install
  - pip install python-coveralls
script:
  - python setup.py test -a --cov=./ --cov-report term-missing
after_success:
  - coveralls